use chrono::{DateTime, Utc};
use sqlx::{Postgres, postgres::PgArguments, query::Query};
use uuid::Uuid;

use crate::parsers::AccessLogEntry;

/// This is a bit painful. Since we'll be using batch inserts via
/// `INSERT INTO ... SELECT * FROM UNNEST`, we need to have each column as its
/// own [Vec<>]. This, unfortunately, would end up in a lot of manual work.
/// This struct is built with some helpers generated by macros to avoid making
/// this too painful, but meh.
pub struct AccessLogColumnVecs {
    pub id: Vec<Uuid>,
    pub hostname: Vec<String>,
    pub ts: Vec<DateTime<Utc>>,
    pub server_name: Vec<Option<String>>,
    pub server_port: Vec<Option<i32>>,
    pub client_addr: Vec<Option<String>>,
    pub client_forwarded_for: Vec<Option<String>>,
    pub client_referer: Vec<Option<String>>,
    pub client_ua: Vec<Option<String>>,
    pub req_host: Vec<Option<String>>,
    pub req_length: Vec<Option<i64>>,
    pub req_method: Vec<Option<String>>,
    pub req_proto: Vec<Option<String>>,
    pub req_scheme: Vec<Option<String>>,
    pub req_uri: Vec<Option<String>>,
    pub res_body_length: Vec<Option<i64>>,
    pub res_duration: Vec<Option<f64>>,
    pub res_length: Vec<Option<i64>>,
    pub res_status: Vec<Option<i32>>,
    pub upstream_addr: Vec<Option<String>>,
    pub upstream_bytes_received: Vec<Option<i64>>,
    pub upstream_bytes_sent: Vec<Option<i64>>,
    pub upstream_cache_status: Vec<Option<String>>,
    pub upstream_connect_time: Vec<Option<f64>>,
    pub upstream_host: Vec<Option<String>>,
    pub upstream_response_length: Vec<Option<i64>>,
    pub upstream_response_time: Vec<Option<f64>>,
    pub upstream_status: Vec<Option<i32>>,
}

/// This macro just exists to reduce pain with defining the functions that are
/// just boring calls to something where the only difference is the field name.
macro_rules! column_vecs_impl {
    (
        $($field:ident),* $(,)?
    ) => {
        impl AccessLogColumnVecs {
            pub fn with_capacity(capacity: usize) -> Self {
                Self {
                    $(
                        $field: Vec::with_capacity(capacity),
                    )*
                }
            }

            pub fn clear(&mut self) {
                $(
                    self.$field.clear();
                )*
            }

            pub fn bind_all<'q>(
                &'q self,
                mut query: Query<'q, Postgres, PgArguments>,
            ) -> Query<'q, Postgres, PgArguments> {
                $(
                    query = query.bind(&self.$field);
                )*
                query
            }

        }
    }
}

/// Likewise, this is just a glorified string replace to make assigning values
/// in the push() fn a bit less verbose.
macro_rules! column_vecs_push_body {
    (
        $self:ident, $entry:ident, {
            $($field:ident: $expr:expr),* $(,)?
        }
    ) => {
        $(
            $self.$field.push($expr);
        )*
    }
}

column_vecs_impl! {
    id,
    hostname,
    ts,
    server_name,
    server_port,
    client_addr,
    client_forwarded_for,
    client_referer,
    client_ua,
    req_host,
    req_length,
    req_method,
    req_proto,
    req_scheme,
    req_uri,
    res_body_length,
    res_duration,
    res_length,
    res_status,
    upstream_addr,
    upstream_bytes_received,
    upstream_bytes_sent,
    upstream_cache_status,
    upstream_connect_time,
    upstream_host,
    upstream_response_length,
    upstream_response_time,
    upstream_status,
}

impl AccessLogColumnVecs {
    pub fn push(&mut self, entry: AccessLogEntry) {
        column_vecs_push_body!(self, entry, {
            id: Uuid::new_v4(),
            ts: entry.ts,
            hostname: entry.hostname,
            server_name: entry.server.name,
            server_port: entry.server.port,
            client_addr: entry.client.addr,
            client_forwarded_for: entry.client.forwarded_for,
            client_referer: entry.client.referer,
            client_ua: entry.client.ua,
            req_host: entry.req.host,
            req_length: entry.req.length,
            req_method: entry.req.method,
            req_proto: entry.req.proto,
            req_scheme: entry.req.scheme,
            req_uri: entry.req.uri,
            res_body_length: entry.res.body_length,
            res_duration: entry.res.duration,
            res_length: entry.res.length,
            res_status: entry.res.status,
            upstream_addr: entry.upstream.addr,
            upstream_bytes_received: entry.upstream.bytes_received,
            upstream_bytes_sent: entry.upstream.bytes_sent,
            upstream_cache_status: entry.upstream.cache_status,
            upstream_connect_time: entry.upstream.connect_time,
            upstream_host: entry.upstream.host,
            upstream_response_length: entry.upstream.response_length,
            upstream_response_time: entry.upstream.response_time,
            upstream_status: entry.upstream.status,
        });
    }
}
